spring:
  application:
    name: autotest-study
  profiles:
    active: dev

server:
  port: 8084
  http2:
    enabled: true
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true
  feign:
    httpclient:
      enabled: false
    okhttp:
      enabled: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml


logging:
  level:
    root: debug
