spring:
  application:
    name: autotest-study
  profiles:
    active: dev

server:
  port: 8084
  http2:
    enabled: true
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256
  feign:
    httpclient:
      enabled: false
    okhttp:
      enabled: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml


logging:
  level:
    root: debug

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}